FROM rapidsai/devcontainers:25.10-cpp-cuda12.9

ARG GIT_BRANCH_NAME
ENV GIT_BRANCH_NAME=${GIT_BRANCH_NAME}

COPY . /accelerated-computing-hub

COPY brev/entrypoint.bash /entrypoint.bash

WORKDIR /accelerated-computing-hub/gpu-cpp-tutorial/notebooks

ENV PIP_ROOT_USER_ACTION=ignore

RUN pip install --root-user-action ignore -r /accelerated-computing-hub/gpu-cpp-tutorial/brev/requirements.txt \
 && git config --unset-all "http.https://github.com/.extraheader" || { code=$?; [ "$code" = 5 ] || exit "$code"; } \
 && git config --global --add safe.directory "/accelerated-computing-hub" \
 && mkdir -p ~/.jupyter/lab/user-settings/jupyterlab-nvidia-nsight \
 && mkdir -p ~/.local/state/._bash_history \
 && ln -fs /accelerated-computing-hub/brev/jupyter_server_config.py ~/.jupyter/jupyter_server_config.py \
 && python -m jupyter labextension disable "@jupyterlab/apputils-extension:announcements"

ENTRYPOINT ["/entrypoint.bash"]

CMD ["/accelerated-computing-hub/brev/jupyter-start.bash"]
