name: &tutorial-name accelerated-python

x-config:
  dockerfile: &dockerfile tutorials/accelerated-python/brev/dockerfile
  image: &image ghcr.io/nvidia/accelerated-python-tutorial:pull-request-108-latest
  working-dir: &working-dir /accelerated-computing-hub/tutorials/accelerated-python/notebooks
  default-jupyter-url: &default-jupyter-url ["/lab/tree/accelerated-computing-hub/tutorials/accelerated-python/notebooks/syllabi/cuda_python__cuda_core_cccl__2_hours.ipynb?file-browser-path=/accelerated-computing-hub/tutorials/accelerated-python/notebooks"]
  gpu-config: &gpu-config
    privileged: true
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  common-service: &common-service
    pull_policy: missing
    volumes:
      - accelerated-computing-hub:/accelerated-computing-hub
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      BREV_ENV_ID: ${BREV_ENV_ID:-}
      ACH_TUTORIAL: *tutorial-name
      ACH_RUN_TESTS: ${ACH_RUN_TESTS:-}
    user: root
    working_dir: *working-dir
  persistent-service: &persistent-service
    depends_on:
      base:
        condition: service_completed_successfully
    restart: unless-stopped

services:
  base:
    <<: [*gpu-config, *common-service]
    image: *image
    entrypoint: ["/accelerated-computing-hub/brev/base-start.bash"]
    build:
      context: ../../..
      dockerfile: *dockerfile
    restart: "no"
  jupyter:
    <<: [*gpu-config, *common-service, *persistent-service]
    image: *image
    command: *default-jupyter-url
    ports:
      - "0.0.0.0:8888:8888" # JupyterLab
  nsight:
    <<: [*gpu-config, *common-service, *persistent-service]
    image: nvcr.io/nvidia/devtools/nsight-streamer-nsys:2025.3.1
    entrypoint: ["/accelerated-computing-hub/brev/nsight-start.bash"]
    ports:
      - "0.0.0.0:8080:8080" # HTTP
      - "0.0.0.0:3478:3478" # TURN

volumes:
  accelerated-computing-hub:
