services:
  jupyter:
    build:
      context: ../../..
      dockerfile: gpu-python-tutorial/v3/brev/dockerfile
    image: ghcr.io/brycelelbach/accelerated-computing-hub/gpu-python-tutorial:latest
    pull_policy: always
    privileged: true
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "0.0.0.0:8888:8888" # JupyterLab
    volumes:
      - /home/ubuntu/accelerated-computing-hub:/accelerated-computing-hub
    environment:
      - BREV_ENV_ID
    user: root
    working_dir: /accelerated-computing-hub/gpu-python-tutorial/v3/notebooks
    restart: unless-stopped
  nsight:
    image: nvcr.io/nvidia/devtools/nsight-streamer-nsys:2025.3.1
    pull_policy: always
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "0.0.0.0:8080:8080" # HTTP
      - "0.0.0.0:3478:3478" # TURN
    volumes:
      - /home/ubuntu/accelerated-computing-hub:/accelerated-computing-hub
    environment:
      - BREV_ENV_ID
    user: root
    working_dir: /accelerated-computing-hub/gpu-python-tutorial/v3/notebooks
    entrypoint: ["/accelerated-computing-hub/brev/nsight-start.bash"]
    restart: unless-stopped
