# SPDX-FileCopyrightText: Copyright (c) 2026 Johnny Nuñez Cano
# SPDX-License-Identifier: MIT
#
# ============================================================================
#  Shared task logic — used by every part of this series
# ============================================================================
#
#  This module is the brain of the pick-and-place task. Every part of the
#  series imports it unchanged, so the *task* stays identical and the only
#  thing that varies is the physics backend you are learning about:
#
#      Article 2 / Part 1   so101_pick_place.py  ->  mujoco.mj_step      (CPU)
#      Article 2 / Part 2   so101_mjwarp.py      ->  mujoco_warp.step    (GPU)
#      Article 3 / Part 3   so101_newton.py      ->  SolverMuJoCo.step() (Newton)
#
#  The same code drives two robots, selected with --robot:
#
#      so101   Robot Studio SO-101 (5-DoF + hinge gripper)
#      rebot   Seeed reBot DevArm  (6-DoF + coupled slide gripper)
#              https://github.com/google-deepmind/mujoco_menagerie/tree/main/seeed_rebot_devarm
#
#  You are NOT asked to modify this file during the exercises.
#
#  Anatomy of the task
#  -------------------
#    1. Scene .............. robot MJCF from Menagerie + a table + two cubes
#    2. Inverse kinematics . damped least squares on the jaw aperture center,
#                           using only stock MuJoCo (mj_jac)
#    3. Controller ......... a small state machine that interpolates between
#                           Cartesian waypoints and ramps the gripper
#    4. Grasp .............. a *real* friction grasp: the jaws close on the
#                           cube's side faces and lift it
#
#  Two lessons that cost real debugging time:
#    * Drive IK to the measured aperture center, not an end-effector site.
#    * Close the gripper gradually. Slamming the jaw shoves the cube away.

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil

import mujoco
import numpy as np

from robots import RobotSpec, get_robot
from utils import resolve_menagerie_robot_path

IK_DAMPING = 1e-3
IK_STEP_SIZE = 0.6
IK_ITERS_PER_FRAME = 24

RED_BODY = "red_cube"
BLUE_BODY = "blue_cube"

# Module-level aliases, rebound by set_active_robot() so
# `import pick_place_common as task; task.TABLE_CENTER` sees the selected robot.
# Do NOT `from pick_place_common import TABLE_CENTER` before resolving the scene.
_active: RobotSpec | None = None
CUBE_HALF = 0.022
TABLE_CENTER = np.zeros(3)
TABLE_HALF_SIZE = np.zeros(3)
RED_CUBE_POS = np.zeros(3)
BLUE_CUBE_POS = np.zeros(3)
STACK_ON_BLUE_Z = 0.0
GRIPPER_OPEN = 0.0
GRIPPER_CLOSED = 0.0
SEED_POSE = np.zeros(6)
HOME_CTRL = np.zeros(6)


def active_robot() -> RobotSpec:
    return _active or get_robot()


def set_active_robot(spec: RobotSpec) -> RobotSpec:
    """Bind layout constants to *spec* so `task.TABLE_CENTER` etc. stay in sync."""
    global _active, CUBE_HALF, TABLE_CENTER, TABLE_HALF_SIZE
    global RED_CUBE_POS, BLUE_CUBE_POS, STACK_ON_BLUE_Z
    global GRIPPER_OPEN, GRIPPER_CLOSED, SEED_POSE, HOME_CTRL
    _active = spec
    CUBE_HALF = spec.cube_half
    TABLE_CENTER = spec.table_center
    TABLE_HALF_SIZE = spec.table_half_size
    RED_CUBE_POS = spec.red_cube_pos
    BLUE_CUBE_POS = spec.blue_cube_pos
    STACK_ON_BLUE_Z = spec.stack_on_blue_z
    GRIPPER_OPEN = spec.gripper_open
    GRIPPER_CLOSED = spec.gripper_closed
    SEED_POSE = spec.home_ctrl.copy()
    HOME_CTRL = spec.home_ctrl.copy()
    return spec


def _scene_xml(spec: RobotSpec) -> str:
    tc, th = spec.table_center_xyz, spec.table_half_xyz
    red, blue = spec.red_cube_pos, spec.blue_cube_pos
    h = spec.cube_half
    return f"""<!--
  Pick & place scene for {spec.display_name}
  Generated by pick_place_common.resolve_pick_place_scene().
  Visual and groundplane boilerplate adapted from the standard scene.xml
  files in MuJoCo Menagerie (google-deepmind/mujoco_menagerie, Apache-2.0).
-->
<mujoco model="{spec.key}_pick_place">
  <include file="{spec.robot_xml}"/>

  <visual>
    <headlight diffuse="0.6 0.6 0.6" ambient="0.3 0.3 0.3" specular="0 0 0"/>
    <rgba haze="0.15 0.25 0.35 1"/>
    <global azimuth="160" elevation="-20"/>
  </visual>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
      markrgb="0.8 0.8 0.8" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>
  </asset>

  <worldbody>
    <light pos="0.3 0 1.5" dir="0 0 -1" directional="true"/>
    <geom name="floor" size="0 0 0.05" type="plane" material="groundplane"/>

    <geom name="table" type="box" pos="{tc[0]} {tc[1]} {tc[2]}" size="{th[0]} {th[1]} {th[2]}"
      rgba="0.32 0.32 0.32 1" friction="1 0.005 0.0005" condim="3"/>

    <body name="red_cube" pos="{red[0]} {red[1]} {red[2]}">
      <freejoint name="red_cube_joint"/>
      <geom name="red_cube" type="box" size="{h} {h} {h}" rgba="0.85 0.05 0.04 1"
        friction="1.2 0.005 0.0005" condim="3" mass="0.08"/>
    </body>

    <body name="blue_cube" pos="{blue[0]} {blue[1]} {blue[2]}">
      <freejoint name="blue_cube_joint"/>
      <geom name="blue_cube" type="box" size="{h} {h} {h}" rgba="0.05 0.20 0.90 1"
        friction="1.2 0.005 0.0005" condim="3" mass="0.08"/>
    </body>
  </worldbody>
</mujoco>
"""


def resolve_pick_place_scene(
    menagerie_root: Path | None = None,
    *,
    explicit: bool = False,
    spec: RobotSpec | None = None,
    robot: str | None = None,
) -> Path:
    """Generate and return the local pick-place scene XML for *spec*."""
    spec = spec or get_robot(robot)
    set_active_robot(spec)
    robot_dir = resolve_menagerie_robot_path(spec, menagerie_root, explicit=explicit)
    generated_dir = Path(__file__).parent / ".generated" / spec.folder
    generated_dir.mkdir(parents=True, exist_ok=True)

    shutil.copyfile(robot_dir / spec.robot_xml, generated_dir / spec.robot_xml)
    assets_link = generated_dir / "assets"
    if assets_link.is_symlink() and not assets_link.exists():
        # Stale symlink whose target no longer exists on this machine
        # (e.g. a moved cache); remove it so it can be recreated locally.
        assets_link.unlink()
    if not assets_link.exists():
        try:
            assets_link.symlink_to(robot_dir / "assets", target_is_directory=True)
        except OSError:
            shutil.copytree(robot_dir / "assets", assets_link)

    scene = generated_dir / "scene_pick_place.xml"
    scene.write_text(_scene_xml(spec))
    return scene


def load_pick_place_model(xml_path: Path, spec: RobotSpec | None = None) -> mujoco.MjModel:
    """Compile the MJCF and optionally boost arm actuator force limits.

    The shipped SO-101 MJCF caps every actuator at 2.94 N·m (STS3215 stall),
    which is too weak to reach a low grasp pose, so we raise the *arm* joints.
    The reBot DevArm already has RS-06 / RS-00 ratings (36 / 14 N·m) and is
    left unchanged.
    """
    spec = spec or active_robot()
    model = mujoco.MjModel.from_xml_path(str(xml_path))
    if spec.arm_force_limit is None:
        return model
    gripper = set(spec.gripper_actuator_names)
    for i in range(model.nu):
        name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_ACTUATOR, i) or ""
        if name in gripper:
            continue
        model.actuator_forcerange[i] = [-spec.arm_force_limit, spec.arm_force_limit]
    return model


def actuator_ctrl_limits(model: mujoco.MjModel) -> tuple[np.ndarray, np.ndarray]:
    """Per-actuator (lower, upper) command bounds."""
    lower = np.empty(model.nu, dtype=np.float64)
    upper = np.empty(model.nu, dtype=np.float64)
    for i in range(model.nu):
        if model.actuator_ctrllimited[i]:
            lower[i], upper[i] = model.actuator_ctrlrange[i]
        else:
            joint_id = model.actuator_trnid[i, 0]
            if joint_id >= 0 and model.jnt_limited[joint_id]:
                lower[i], upper[i] = model.jnt_range[joint_id]
            else:
                lower[i], upper[i] = -np.pi, np.pi
    return lower, upper


def apply_arm_ctrl(model: mujoco.MjModel, data: mujoco.MjData, ctrl: np.ndarray) -> None:
    """Snap a scratch MjData to a joint configuration, then run FK.

    Used **only on the IK scratch state** — never on the live simulation.
    """
    lower, upper = actuator_ctrl_limits(model)
    ctrl = np.clip(ctrl, lower, upper)
    data.ctrl[: model.nu] = ctrl
    for i in range(model.nu):
        joint_id = model.actuator_trnid[i, 0]
        if joint_id >= 0:
            data.qpos[model.jnt_qposadr[joint_id]] = ctrl[i]
    mujoco.mj_forward(model, data)


def reset_cubes(model: mujoco.MjModel, data: mujoco.MjData, spec: RobotSpec | None = None) -> None:
    """Reset free-joint cube poses to their spawn positions."""
    spec = spec or active_robot()
    for body_name, pos in ((RED_BODY, spec.red_cube_pos), (BLUE_BODY, spec.blue_cube_pos)):
        body_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, body_name)
        joint_id = model.body_jntadr[body_id]
        if joint_id < 0:
            continue
        qadr = model.jnt_qposadr[joint_id]
        data.qpos[qadr : qadr + 3] = pos
        data.qpos[qadr + 3 : qadr + 7] = [1, 0, 0, 0]
        dadr = model.jnt_dofadr[joint_id]
        data.qvel[dadr : dadr + 6] = 0.0
    mujoco.mj_forward(model, data)


def geom_centroid(model: mujoco.MjModel, data: mujoco.MjData, names: tuple[str, ...]) -> np.ndarray:
    """Mean world position of the named geoms (requires a prior forward pass)."""
    positions = []
    for name in names:
        geom_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_GEOM, name)
        if geom_id < 0:
            raise ValueError(f"Geom '{name}' not found in model.")
        positions.append(data.geom_xpos[geom_id])
    return np.mean(np.asarray(positions), axis=0)


def aperture_center(model: mujoco.MjModel, data: mujoco.MjData, spec: RobotSpec | None = None) -> np.ndarray:
    """World point exactly between the two jaws.

    THIS is the grasp point we drive IK to — not a named site, which often sits
    above and behind the real finger gap.
    """
    spec = spec or active_robot()
    if spec.left_jaw_geoms and spec.right_jaw_geoms:
        left = geom_centroid(model, data, spec.left_jaw_geoms)
        right = geom_centroid(model, data, spec.right_jaw_geoms)
        return 0.5 * (left + right)
    if not spec.left_jaw_body or not spec.right_jaw_body:
        raise ValueError(f"Robot {spec.key} has no jaw geoms or jaw bodies configured.")
    left_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, spec.left_jaw_body)
    right_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, spec.right_jaw_body)
    if left_id < 0 or right_id < 0:
        raise ValueError(f"Jaw bodies not found: {spec.left_jaw_body}, {spec.right_jaw_body}")
    return 0.5 * (data.xpos[left_id] + data.xpos[right_id])


def _apply_gripper_and_locks(ctrl: np.ndarray, gripper: float, spec: RobotSpec) -> None:
    if spec.wrist_lock_index is not None:
        ctrl[spec.wrist_lock_index] = spec.wrist_lock_value
    for i in spec.gripper_ctrl_indices:
        ctrl[i] = gripper


def ik_to_target(
    model: mujoco.MjModel,
    data: mujoco.MjData,
    target_pos: np.ndarray,
    ctrl: np.ndarray,
    *,
    gripper: float,
    iters: int = IK_ITERS_PER_FRAME,
    spec: RobotSpec | None = None,
) -> np.ndarray:
    """Damped-least-squares position IK on the jaw aperture center."""
    spec = spec or active_robot()
    body_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, spec.gripper_body)
    if body_id < 0:
        raise ValueError(f"Body '{spec.gripper_body}' not found in model.")

    lower, upper = actuator_ctrl_limits(model)
    ctrl = np.clip(ctrl.copy(), lower, upper)
    _apply_gripper_and_locks(ctrl, gripper, spec)
    jacp = np.zeros((3, model.nv))
    jacr = np.zeros((3, model.nv))

    for _ in range(iters):
        apply_arm_ctrl(model, data, ctrl)
        point = aperture_center(model, data, spec)
        err = target_pos - point
        if np.linalg.norm(err) < 1e-4:
            break
        mujoco.mj_jac(model, data, jacp, jacr, point, body_id)
        cols = [jacp[:, model.jnt_dofadr[model.actuator_trnid[i, 0]]] for i in spec.free_arm_joints]
        jac = np.array(cols).T
        jjt = jac @ jac.T + IK_DAMPING * np.eye(3)
        dq = jac.T @ np.linalg.solve(jjt, err)
        for k, i in enumerate(spec.free_arm_joints):
            ctrl[i] += IK_STEP_SIZE * dq[k]
        ctrl = np.clip(ctrl, lower, upper)
        _apply_gripper_and_locks(ctrl, gripper, spec)

    return np.clip(ctrl, lower, upper)


@dataclass(frozen=True)
class Waypoint:
    """One step of the scripted task."""

    name: str
    target: np.ndarray
    gripper: float
    duration: float


def build_auto_sequence(spec: RobotSpec | None = None) -> list[Waypoint]:
    """Pick the red cube and stack it on the blue cube (real friction grasp)."""
    spec = spec or active_robot()
    red = spec.red_cube_pos.copy()
    blue = spec.blue_cube_pos.copy()
    stack = np.array([blue[0], blue[1], spec.stack_on_blue_z])
    open_g, closed_g = spec.gripper_open, spec.gripper_closed
    h = spec.approach_height
    return [
        Waypoint("above_red", red + [0, 0, h], open_g, 1.2),
        Waypoint("descend_red", red, open_g, 1.4),
        Waypoint("grasp_red", red, closed_g, 1.6),
        Waypoint("lift_red", red + [0, 0, h + 0.05], closed_g, 1.4),
        Waypoint("above_blue", blue + [0, 0, h + 0.07], closed_g, 1.6),
        Waypoint("place_stack", stack, closed_g, 1.4),
        Waypoint("release", stack, open_g, 1.0),
        Waypoint("retreat", blue + [0, 0, h + 0.09], open_g, 1.0),
    ]


class PickPlaceController:
    """Scripted state machine that turns waypoints into per-frame joint targets."""

    def __init__(self, sequence: list[Waypoint] | None = None, spec: RobotSpec | None = None):
        self.spec = spec or active_robot()
        self.sequence = sequence or build_auto_sequence(self.spec)
        self.phase = 0
        self.timer = 0.0
        self.ctrl = self.spec.home_ctrl.copy()
        self.ik_data: mujoco.MjData | None = None
        self.start_target = self.sequence[0].target.copy()
        self.goal_target = self.sequence[0].target.copy()
        self.start_gripper = float(self.spec.home_ctrl[self.spec.gripper_ctrl_indices[0]])
        self.goal_gripper = float(self.sequence[0].gripper)

    def reset(self) -> None:
        self.phase = 0
        self.timer = 0.0
        self.ctrl = self.spec.home_ctrl.copy()
        self.ik_data = None
        self.start_target = self.sequence[0].target.copy()
        self.goal_target = self.sequence[0].target.copy()
        self.start_gripper = float(self.spec.home_ctrl[self.spec.gripper_ctrl_indices[0]])
        self.goal_gripper = float(self.sequence[0].gripper)

    @property
    def done(self) -> bool:
        return self.phase >= len(self.sequence)

    def phase_name(self) -> str:
        if self.done:
            return "done"
        return self.sequence[self.phase].name

    def _ensure_ik_data(self, model: mujoco.MjModel) -> mujoco.MjData:
        if self.ik_data is None:
            self.ik_data = mujoco.MjData(model)
            apply_arm_ctrl(model, self.ik_data, self.ctrl)
        return self.ik_data

    def _advance_goal(self) -> None:
        self.phase += 1
        self.timer = 0.0
        if self.done:
            return
        self.start_target = self.goal_target.copy()
        self.start_gripper = self.goal_gripper
        self.goal_target = self.sequence[self.phase].target.copy()
        self.goal_gripper = float(self.sequence[self.phase].gripper)

    def step(self, model: mujoco.MjModel, data: mujoco.MjData, frame_dt: float) -> np.ndarray:
        if self.done:
            return self.ctrl

        wp = self.sequence[self.phase]
        duration = max(wp.duration, 1e-6)
        alpha = np.clip(self.timer / duration, 0.0, 1.0)
        alpha = alpha * alpha * (3.0 - 2.0 * alpha)
        target = (1.0 - alpha) * self.start_target + alpha * self.goal_target
        gripper = (1.0 - alpha) * self.start_gripper + alpha * self.goal_gripper

        ik_data = self._ensure_ik_data(model)
        self.ctrl = ik_to_target(
            model, ik_data, target, self.ctrl, gripper=gripper, spec=self.spec
        )
        self.timer += frame_dt
        if self.timer >= wp.duration:
            self._advance_goal()
        return self.ctrl


def apply_viewer_camera(viewer, spec: RobotSpec | None = None) -> None:
    spec = spec or active_robot()
    viewer.cam.azimuth = 140
    viewer.cam.elevation = -25
    viewer.cam.distance = spec.camera_distance
    viewer.cam.lookat[:] = spec.camera_lookat
