FROM ubuntu:24.04 AS artifacts

COPY . /accelerated-computing-hub
RUN find /accelerated-computing-hub/tutorials \
    -mindepth 1 -maxdepth 1 -type d -not -name "floating-point-emulation" \
    -exec rm -rf {} +
RUN rm -rf /accelerated-computing-hub/.git

FROM nvidia/cuda:13.1.0-base-ubuntu24.04

# Install CUDA Toolkit + build tools
RUN apt update -y \
    && apt install -y wget \
    && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
    && echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null \
    && apt update -y \
    && apt install -y cuda-nvrtc-13-1 cuda-cccl-13-1 libcublas-dev-13-1 \
    libnvjitlink-13-1 cuda-cudart-13-1 cuda-nvcc-13-1 libnvvm-13-1 \
    python-is-python3 python3-venv \
    build-essential cmake \
    && apt-get clean -y

# Install MathDx
RUN wget https://developer.nvidia.com/downloads/compute/cublasdx/redist/cublasdx/cuda13/nvidia-mathdx-25.12.1-cuda13.tar.gz \
    && tar -xvf nvidia-mathdx-25.12.1-cuda13.tar.gz \
    && rm nvidia-mathdx-25.12.1-cuda13.tar.gz \
    && mkdir -p /opt/nvidia \
    && mv nvidia-mathdx-25.12.1-cuda13/nvidia/mathdx /opt/nvidia/mathdx \
    && rm -rf nvidia-mathdx-25.12.1-cuda13

# Install libmathdx
RUN wget https://developer.nvidia.com/downloads/compute/cublasdx/redist/cublasdx/cuda13/libmathdx-Linux-x86_64-0.3.1-cuda13.0.tar.gz \
    && mkdir -p /opt/nvidia/libmathdx \
    && tar -xvf libmathdx-Linux-x86_64-0.3.1-cuda13.0.tar.gz -C /opt/nvidia/libmathdx \
    && rm libmathdx-Linux-x86_64-0.3.1-cuda13.0.tar.gz

# Install python
RUN python -m venv /opt/venv
ENV ACH_TUTORIAL=floating-point-emulation \
    CUDA_PATH=/usr/local/cuda-13.1 \
    PATH="/opt/venv/bin:$PATH" \
    LD_LIBRARY_PATH="/opt/nvidia/libmathdx/lib:$LD_LIBRARY_PATH"

COPY tutorials/${ACH_TUTORIAL}/brev/requirements.txt /opt/requirements.txt

RUN set -ex \
 && `# Install Python packages` \
     && pip install --no-cache-dir -r /opt/requirements.txt \
     && rm /opt/requirements.txt

RUN set -ex \
 && `# Setup JupyterLab` \
     && mkdir -p ~/.jupyter \
     && ln -fs /accelerated-computing-hub/brev/jupyter-server-config.py ~/.jupyter/jupyter_server_config.py \
     && mkdir -p ~/.ipython/profile_default/startup \
     && ln -fs /accelerated-computing-hub/brev/ipython-startup-add-cwd-to-path.py ~/.ipython/profile_default/startup/00-add-cwd-to-path.py \
     && python -m jupyter labextension disable "@jupyterlab/apputils-extension:announcements"

COPY --from=artifacts /accelerated-computing-hub /accelerated-computing-hub

WORKDIR /accelerated-computing-hub/tutorials/${ACH_TUTORIAL}/notebooks

ENTRYPOINT ["/accelerated-computing-hub/brev/jupyter-start.bash"]
