FROM ghcr.io/nvidia/mirrors/pytorch-2.9.0-cuda12.8-cudnn9-runtime

ENV ACH_TUTORIAL=nvmath-python \
    PIP_ROOT_USER_ACTION=ignore \
    CUPY_CACHE_DIR=/tmp/cupy_cache \
    MPLCONFIGDIR=/tmp/matplotlib_cache

# Copy only requirements.txt first for better Docker layer caching.
COPY tutorials/${ACH_TUTORIAL}/brev/requirements.txt /opt/requirements.txt

RUN set -ex \
 && `# Install Python packages` \
     && pip install --no-cache-dir --root-user-action=ignore -r /opt/requirements.txt \
     && rm -f /opt/requirements.txt \
 && `# Install system packages` \
     && apt-get update -y \
     && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git-lfs gosu sudo \
     && apt-get clean -y \
     && rm -rf /var/lib/apt/lists/*

# Disable unnecessary default Jupyter extensions.
RUN python -m jupyter labextension disable "@jupyterlab/apputils-extension:announcements" \
 && python -m jupyter labextension disable "@jupyterlab/console-extension:tracker"

# Enable passwordless sudo for all users and pass through environment and path
RUN echo 'ALL ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
 && sed -i -e 's/^Defaults\s*env_reset/Defaults !env_reset/' -e 's/^Defaults\s*secure_path=/#&/' /etc/sudoers

# Install Docker
RUN apt-get update -y \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
 && mkdir -p /etc/apt/keyrings \
 && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
 && apt-get update -y \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin \
 && apt-get clean -y \
 && rm -rf /var/lib/apt/lists/*

COPY --chmod=0777 . /accelerated-computing-hub

WORKDIR /accelerated-computing-hub/tutorials/${ACH_TUTORIAL}/notebooks

ENTRYPOINT ["/accelerated-computing-hub/brev/entrypoint.bash", "jupyter"]
