#! /bin/bash
#
# Entrypoint for the nsight service. Runs as root to do setup, then hands off
# to the nsight streamer's own entrypoint which handles user switching.

set -euo pipefail

# Set USER for nsight streamer's internal user switching
export USER="${ACH_TARGET_USER}"
export HOME="${ACH_TARGET_HOME}"

# Nsight Streamer constructs HOME as /home/$USER in its supervisor config.
# Rootless Podman runs the bind-mounted checkout as root, whose real home is
# /root, so provide the path the Streamer expects.
STREAMER_HOME="/home/${ACH_TARGET_USER}"
if [ "${ACH_TARGET_HOME}" != "${STREAMER_HOME}" ] && \
   [ ! -e "${STREAMER_HOME}" ] && [ ! -L "${STREAMER_HOME}" ]; then
    ln -s "${ACH_TARGET_HOME}" "${STREAMER_HOME}"
fi

# The pinned Streamer images wait specifically for the X4 filesystem socket.
# With host networking the two X servers need distinct display numbers because
# their abstract sockets share a network namespace. Let the ncu service use X5
# while satisfying the upstream readiness check with a filesystem symlink.
DISPLAY_NUMBER="${DISPLAY:-:4}"
DISPLAY_NUMBER="${DISPLAY_NUMBER#:}"
if [ "${DISPLAY_NUMBER}" != "4" ]; then
    mkdir -p /tmp/.X11-unix
    ln -sfn "X${DISPLAY_NUMBER}" /tmp/.X11-unix/X4
fi

# Ensure a group with the user's name exists.
# The Nsight Streamer's entrypoint does `chown $USER:$USER` which requires a group
# with the same name as the user. Our main entrypoint may have reused an existing
# group with a different name if the target GID was already taken.
if ! getent group "${ACH_TARGET_USER}" &>/dev/null; then
    groupadd "${ACH_TARGET_USER}" || true
fi

# Copy bashrc and Nsight config from nvidia user to target user's home (skip if same user)
if [ "${ACH_TARGET_HOME}" != "/home/nvidia" ]; then
    mkdir -p "${ACH_TARGET_HOME}/.config/NVIDIA Corporation"
    if [ -f "/home/nvidia/.config/NVIDIA Corporation/NVIDIA Nsight Systems.ini" ]; then
        cp "/home/nvidia/.config/NVIDIA Corporation/NVIDIA Nsight Systems.ini" "${ACH_TARGET_HOME}/.config/NVIDIA Corporation/"
    fi
    cp /home/nvidia/.bashrc "${ACH_TARGET_HOME}/.bashrc"
    chown -R "${ACH_TARGET_USER}:$(id -gn "${ACH_TARGET_USER}")" "${ACH_TARGET_HOME}"
fi

# Generate Nsight Compute config with the tutorial's notebooks as the default folder
mkdir -p "${ACH_TARGET_HOME}/.config/NVIDIA Corporation"
echo "[CorePlugin.Environment]" > "${ACH_TARGET_HOME}/.config/NVIDIA Corporation/NVIDIA Nsight Compute.ini"
echo "CorePlugin.DefaultDocumentsFolder=/accelerated-computing-hub/tutorials/${ACH_TUTORIAL}/notebooks" >> "${ACH_TARGET_HOME}/.config/NVIDIA Corporation/NVIDIA Nsight Compute.ini"

# Curl is only needed to discover a public TURN address. Tunnels provide an
# explicit address and should not mutate the published Streamer image.
if ! command -v curl &> /dev/null && [ -z "${SELKIES_TURN_HOST:-}" ]; then
    apt-get update
    apt-get install -y curl
fi

# Load TURN credentials generated by the base service
TURN_CREDENTIALS_FILE="/accelerated-computing-hub/.turn-credentials"
if [ -z "${TURN_USERNAME:-}" ] || [ -z "${TURN_PASSWORD:-}" ]; then
    if [ -f "${TURN_CREDENTIALS_FILE}" ]; then
        source "${TURN_CREDENTIALS_FILE}"
    else
        echo "Warning: TURN credentials file not found at ${TURN_CREDENTIALS_FILE}" >&2
    fi
fi

# Set environment variables for Nsight Streamer
export NVIDIA_DRIVER_CAPABILITIES=all
export HOST_IP="${HOST_IP:-0.0.0.0}"
export WEB_USERNAME="${WEB_USERNAME:-}"
export WEB_PASSWORD="${WEB_PASSWORD:-}"
export SELKIES_ADDR="${SELKIES_ADDR:-0.0.0.0}"
export SELKIES_TURN_HOST="${SELKIES_TURN_HOST:-$(curl -sSL ifconfig.me)}"

VARS=("NVIDIA_DRIVER_CAPABILITIES" "HOST_IP" "WEB_USERNAME" "WEB_PASSWORD" "SELKIES_ADDR" "SELKIES_TURN_HOST")
OPTIONAL_VARS=("TURN_USERNAME" "TURN_PASSWORD" "HTTP_PORT" "TURN_PORT" "SELKIES_ENABLE_HTTPS" "SELKIES_HTTPS_CERT" "SELKIES_HTTPS_KEY")
for VAR in "${OPTIONAL_VARS[@]}"; do
  if [ -n "${!VAR+x}" ]; then
    export "${VAR}"
    VARS+=("${VAR}")
  fi
done

for VAR in "${VARS[@]}"; do
  if [[ -n "${!VAR+x}" ]]; then
    printf 'export %s=%q\n' "${VAR}" "${!VAR}" >> "${HOME}/.bashrc"
  fi
done

# Hand off to nsight streamer's entrypoint (which handles user switching via USER env var)
source /setup/entrypoint.sh "$@"
