#! /bin/bash
#
# Generate a CSCS Slurm Container Engine EDF for a tutorial image.
#
# The EDF can be used on CSCS systems with Slurm's container support, e.g.:
#   srun --environment=${SCRATCH}/ach/pyhpc.toml bash

set -eu

SCRIPT_PATH=$(cd $(dirname ${0}); pwd -P)
REPO_ROOT=$(cd ${SCRIPT_PATH}/..; pwd -P)

usage() {
    cat << USAGE
Usage: $(basename "$0") [options] <tutorial-name|tutorial-dir|docker-compose-file>

Options:
  --image IMAGE       Container image URI (default: image from docker-compose.yml)
  --tag TAG           Replace the image tag before writing the EDF
  --output FILE       EDF output path (default: <tutorial>/brev/cscs.toml)
  --mount             Bind-mount this repository at /accelerated-computing-hub
  --no-mount          Do not bind-mount this repository (default)
  --workdir DIR       Working directory inside the container (default: compose working_dir)

Generate a CSCS Slurm Container Engine EDF for use on systems where the
interactive Docker Compose stack is not available.
USAGE
    exit 1
}

IMAGE=""
IMAGE_TAG=""
OUTPUT=""
MOUNT=false
WORKDIR=""

format_cscs_image_ref() {
    local image_ref=$1
    local registry=${image_ref%%/*}

    if [[ "${image_ref}" == /* ]] || [[ "${image_ref}" == *#* ]]; then
        echo "${image_ref}"
    elif [[ "${registry}" == *.* ]] || [[ "${registry}" == *:* ]] || [ "${registry}" = "localhost" ]; then
        echo "${registry}#${image_ref#*/}"
    else
        echo "${image_ref}"
    fi
}

while [ $# -gt 0 ]; do
    case "$1" in
        --image) IMAGE="$2"; shift 2 ;;
        --tag) IMAGE_TAG="$2"; shift 2 ;;
        --output) OUTPUT="$2"; shift 2 ;;
        --mount) MOUNT=true; shift ;;
        --no-mount) MOUNT=false; shift ;;
        --workdir) WORKDIR="$2"; shift 2 ;;
        -h|--help) usage ;;
        --*) echo "Error: unknown option $1" >&2; usage ;;
        *) break ;;
    esac
done

[ $# -eq 1 ] || usage
ARG=$1

if [[ "${ARG}" == *"/"* ]]; then
    ARG_PATH="${ARG}"
    [[ "${ARG_PATH}" == /* ]] || ARG_PATH="${REPO_ROOT}/${ARG_PATH}"
    if [ -d "${ARG_PATH}" ]; then
        TUTORIAL_DIR="${ARG_PATH}"
        COMPOSE_FILE="${TUTORIAL_DIR}/brev/docker-compose.yml"
    else
        COMPOSE_FILE="${ARG_PATH}"
        TUTORIAL_DIR=$(dirname "$(dirname "${COMPOSE_FILE}")")
    fi
    ACH_TUTORIAL=$(basename "${TUTORIAL_DIR}")
else
    ACH_TUTORIAL="${ARG}"
    TUTORIAL_DIR="${REPO_ROOT}/tutorials/${ACH_TUTORIAL}"
    COMPOSE_FILE="${TUTORIAL_DIR}/brev/docker-compose.yml"
fi

if [ ! -f "${COMPOSE_FILE}" ]; then
    echo "Error: compose file not found: ${COMPOSE_FILE}" >&2
    exit 1
fi

if [ -z "${IMAGE}" ]; then
    IMAGE=$(awk '/image:[[:space:]]*&image[[:space:]]/ {print $3; exit}' "${COMPOSE_FILE}")
fi
if [ -n "${IMAGE_TAG}" ]; then
    IMAGE="${IMAGE%%:*}:${IMAGE_TAG}"
fi
IMAGE=$(format_cscs_image_ref "${IMAGE}")
if [ -z "${WORKDIR}" ]; then
    WORKDIR=$(awk '/working-dir:[[:space:]]*&working-dir[[:space:]]/ {print $3; exit}' "${COMPOSE_FILE}")
fi
if [ -z "${OUTPUT}" ]; then
    OUTPUT="${TUTORIAL_DIR}/brev/cscs.toml"
fi

mkdir -p "$(dirname "${OUTPUT}")"
{
    echo "# Generated by accelerated-computing-hub/brev/generate-cscs-edf.bash"
    echo "# Tutorial: ${ACH_TUTORIAL}"
    echo "image = \"${IMAGE}\""
    echo "workdir = \"${WORKDIR:-/accelerated-computing-hub}\""
    echo "mounts = ["
    if [ "${MOUNT}" = "true" ]; then
        echo "  \"${REPO_ROOT}:/accelerated-computing-hub\","
    fi
    echo "]"
    echo "[env]"
    echo "ACH_TUTORIAL = \"${ACH_TUTORIAL}\""
    echo "ACH_USER = \"${ACH_USER:-ach}\""
    echo "ACH_UID = \"${ACH_UID:-1000}\""
    echo "ACH_GID = \"${ACH_GID:-1000}\""
    if [ "${ACH_TUTORIAL}" = "pyhpc" ]; then
        echo "PMIX_MCA_gds = \"hash\""
        echo "PMIX_MCA_psec = \"native\""
    fi
} > "${OUTPUT}"

echo "Generated CSCS EDF: ${OUTPUT}"
echo "Image: ${IMAGE}"
