#! /bin/bash

set -eu

JUPYTER_HOST="jupyter0-${BREV_ENV_ID:-local}.brevlab.com"
NSYS_HTTP_URL="https://nsys0-${BREV_ENV_ID:-local}.brevlab.com"

# Theme
mkdir -p "${HOME}/.jupyter/lab/user-settings/@jupyterlab/apputils-extension"
cat << EOF > "${HOME}/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings"
{
  "theme": "JupyterLab Dark",
  "adaptive-theme": true,
  "preferred-light-theme": "JupyterLab Light",
  "preferred-dark-theme": "JupyterLab Dark",
  "theme-scrollbars": false
}
EOF

# Load TURN credentials generated by the base service
TURN_CREDENTIALS_FILE="/accelerated-computing-hub/.turn-credentials"
if [ -f "${TURN_CREDENTIALS_FILE}" ]; then
    source "${TURN_CREDENTIALS_FILE}"
else
    echo "Warning: TURN credentials file not found at ${TURN_CREDENTIALS_FILE}" >&2
fi

# Nsight JupyterLab Plugin
mkdir -p "${HOME}/.jupyter/lab/user-settings/jupyterlab-nvidia-nsight"

TURN_SETTINGS=""
if [ -n "${TURN_USERNAME+x}" ] && [ -n "${TURN_PASSWORD+x}" ]; then
    TURN_SETTINGS=$(cat <<TURN
,
    "turnUsername": "${TURN_USERNAME}",
    "turnPassword": "${TURN_PASSWORD}"
TURN
)
fi

cat << EOF > "${HOME}/.jupyter/lab/user-settings/jupyterlab-nvidia-nsight/plugin.jupyterlab-settings"
{
  "ui": {
    "enabled": true,
    "suppressServerAddressWarning": true,
    "host": "${JUPYTER_HOST}",
    "dockerHost": "${JUPYTER_HOST}",
    "defaultStreamerAddress": "${NSYS_HTTP_URL}"${TURN_SETTINGS}
  }
}
EOF

# Execution timing
mkdir -p "${HOME}/.jupyter/lab/user-settings/@jupyterlab/notebook-extension"
cat << EOF > "${HOME}/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings"
{
  "recordTiming": true
}
EOF
