services:
  nsight:
    image: nvcr.io/nvidia/devtools/nsight-streamer-nsys:2025.3.1
    depends_on:
      base:
        condition: service_completed_successfully
    pull_policy: missing
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "0.0.0.0:8080:8080" # HTTP
      - "0.0.0.0:3478:3478" # TURN
    environment:
      - BREV_ENV_ID
    user: root
    entrypoint: ["/accelerated-computing-hub/brev/nsight-start.bash"]
    restart: "unless-stopped"
