FROM ghcr.io/nvidia/mirrors/rapidsai-devcontainers-25.10-cpp-cuda12.9

ENV ACH_TUTORIAL=cuda-cpp \
    ACH_NSYS_PATH=/usr/local/cuda-12.9/bin/nsys \
    ACH_NCU_PATH=/usr/local/cuda-12.9/bin/ncu \
    PATH=/accelerated-computing-hub/brev/wrappers:${PATH} \
    PIP_ROOT_USER_ACTION=ignore \
    CUPY_CACHE_DIR=/tmp/cupy_cache \
    MPLCONFIGDIR=/tmp/matplotlib_cache

# Copy only requirements.txt first for better Docker layer caching.
COPY tutorials/${ACH_TUTORIAL}/brev/requirements.txt /opt/requirements.txt

RUN set -ex \
 && `# Install Python packages` \
     && pip install --no-cache-dir --root-user-action=ignore -r /opt/requirements.txt \
     && rm -f /opt/requirements.txt \
 && `# Install system packages` \
     && apt-get update -y \
     && apt-get install -y --no-install-recommends ffmpeg git-lfs gosu sudo \
     && apt-get clean -y \
     && rm -rf /var/lib/apt/lists/*

# Disable unnecessary default Jupyter extensions.
RUN python -m jupyter labextension disable "@jupyterlab/apputils-extension:announcements" \
 && python -m jupyter labextension disable "@jupyterlab/console-extension:tracker"

# Enable passwordless sudo for all users and pass through environment and path
RUN echo 'ALL ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
 && sed -i -e 's/^Defaults\s*env_reset/Defaults !env_reset/' -e 's/^Defaults\s*secure_path=/#&/' /etc/sudoers

COPY . /accelerated-computing-hub

# Ensure accelerated-computing-hub directory is writable by any user
RUN chmod -R a+rwX /accelerated-computing-hub

WORKDIR /accelerated-computing-hub/tutorials/${ACH_TUTORIAL}/notebooks

ENTRYPOINT ["/accelerated-computing-hub/brev/entrypoint.bash", "jupyter"]
