x-config:
  # Relative paths are resolved from the directory of the Docker Compose file.
  # If we're not on Brev, the Docker Compose file is in the Git repository.
  # If we're on Brev, the Docker Compose file is in /home/ubuntu/workspace, and the Git
  # repository is in /home/ubuntu/accelerated-computing-hub.
  # Thus on Brev, ../.. resolves to /home, and we need to add accelerated-computing-hub/ to get
  # to the Git repository.
  ach-volume: &ach-volume ../..${BREV_ENV_ID:+/ubuntu/accelerated-computing-hub}:/accelerated-computing-hub
  dockerfile: &dockerfile tutorials/cuda-cpp/brev/dockerfile
  image: &image ghcr.io/nvidia/cuda-cpp-tutorial:brev-reorg-latest
  working-dir: &working-dir /accelerated-computing-hub/tutorials/cuda-cpp/notebooks

services:
  base:
    build:
      context: ../../..
      dockerfile: *dockerfile
      args:
        GIT_BRANCH_NAME: ${GIT_BRANCH_NAME:-HEAD}
    image: *image
    pull_policy: missing
    volumes:
      - *ach-volume
    environment:
      - BREV_ENV_ID
    user: root
    working_dir: *working-dir
    entrypoint: ["/update-git-branch.bash"]
    restart: "no"
  jupyter:
    image: *image
    depends_on:
      base:
        condition: service_completed_successfully
    privileged: true
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "0.0.0.0:8888:8888" # JupyterLab
    volumes:
      - *ach-volume
    environment:
      - BREV_ENV_ID
    user: root
    working_dir: *working-dir
    restart: "unless-stopped"
  nsight:
    image: nvcr.io/nvidia/devtools/nsight-streamer-nsys:2025.3.1
    depends_on:
      base:
        condition: service_completed_successfully
    pull_policy: missing
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "0.0.0.0:8080:8080" # HTTP
      - "0.0.0.0:3478:3478" # TURN
    volumes:
      - *ach-volume
    environment:
      - BREV_ENV_ID
    user: root
    working_dir: *working-dir
    entrypoint: ["/accelerated-computing-hub/brev/nsight-start.bash"]
    restart: "unless-stopped"
