FROM rapidsai/devcontainers:25.10-cpp-cuda12.9

ENV PIP_ROOT_USER_ACTION=ignore \
    ACH_TUTORIAL=cuda-cpp

# Copy only requirements.txt first for better Docker layer caching.
COPY tutorials/${ACH_TUTORIAL}/brev/requirements.txt /opt/requirements.txt

RUN set -ex \
 && `# Install Python packages` \
     && pip install --no-cache-dir --root-user-action=ignore -r /opt/requirements.txt \
     && rm -f /opt/requirements.txt \
 && `# Install system packages` \
     && apt-get update -y \
     && apt-get install -y --no-install-recommends ffmpeg git-lfs \
     && apt-get clean -y \
     && rm -rf /var/lib/apt/lists/* \
 && `# Setup Bash` \
     && mkdir -p ~/.local/state/._bash_history \
 && `# Setup JupyterLab` \
     && mkdir -p ~/.jupyter \
     && ln -fs /accelerated-computing-hub/brev/jupyter-server-config.py ~/.jupyter/jupyter_server_config.py \
     && mkdir -p ~/.ipython/profile_default/startup \
     && ln -fs /accelerated-computing-hub/brev/ipython-startup-add-cwd-to-path.py ~/.ipython/profile_default/startup/00-add-cwd-to-path.py \
     && python -m jupyter labextension disable "@jupyterlab/apputils-extension:announcements"

COPY . /accelerated-computing-hub

WORKDIR /accelerated-computing-hub/tutorials/${ACH_TUTORIAL}/notebooks

RUN `# Setup Git` \
     && git config --unset-all "http.https://github.com/.extraheader" || { code=$?; [ "$code" = 5 ] || exit "$code"; } \
     && git config --global --add safe.directory "/accelerated-computing-hub"

ENTRYPOINT ["/accelerated-computing-hub/brev/jupyter-start.bash"]
