FROM ghcr.io/nvidia/mirrors/rapidsai-devcontainers-25.10-cpp-cuda12.9

ENV PIP_ROOT_USER_ACTION=ignore \
    ACH_TUTORIAL=cuda-cpp

# Copy only requirements.txt first for better Docker layer caching.
COPY tutorials/${ACH_TUTORIAL}/brev/requirements.txt /opt/requirements.txt

RUN set -ex \
 && `# Install Python packages` \
     && pip install --no-cache-dir --root-user-action=ignore -r /opt/requirements.txt \
     && rm -f /opt/requirements.txt \
 && `# Install system packages` \
     && apt-get update -y \
     && apt-get install -y --no-install-recommends ffmpeg git-lfs gosu sudo \
     && apt-get clean -y \
     && rm -rf /var/lib/apt/lists/* \
 && `# Disable Jupyter announcements` \
     && python -m jupyter labextension disable "@jupyterlab/apputils-extension:announcements"

# Enable passwordless sudo for all users and pass through environment and path
RUN echo 'ALL ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
 && sed -i -e 's/^Defaults\s*env_reset/#&/' -e 's/^Defaults\s*secure_path=/#&/' /etc/sudoers

# Install Docker
RUN apt-get update -y \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
 && mkdir -p /etc/apt/keyrings \
 && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
 && apt-get update -y \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin \
 && apt-get clean -y \
 && rm -rf /var/lib/apt/lists/*

COPY . /accelerated-computing-hub

# Ensure accelerated-computing-hub directory is writable by any user
RUN chmod -R a+rwX /accelerated-computing-hub

WORKDIR /accelerated-computing-hub/tutorials/${ACH_TUTORIAL}/notebooks

ENTRYPOINT ["/accelerated-computing-hub/brev/entrypoint.bash", "jupyter"]
