x-config:
  # Relative paths are resolved from the directory of the Docker Compose file.
  # If we're not on Brev, the Docker Compose file is in the Git repository.
  # If we're on Brev, the Docker Compose file is in /home/ubuntu/workspace, and the Git
  # repository is in /home/ubuntu/accelerated-computing-hub.
  # Thus on Brev, ../.. resolves to /home, and we need to add accelerated-computing-hub/ to get
  # to the Git repository.
  ach-volume: &ach-volume ../..${BREV_ENV_ID:+/ubuntu/accelerated-computing-hub}:/accelerated-computing-hub
  docker-compose-base: &docker-compose-base https://github.com/NVIDIA/accelerated-computing-hub.git#brev-reorg:brev/docker-compose-base.yml
  dockerfile: &dockerfile tutorials/accelerated-python/brev/dockerfile
  image: &image ghcr.io/nvidia/accelerated-python-tutorial:brev-reorg-latest
  working-dir: &working-dir /accelerated-computing-hub/tutorials/accelerated-python/notebooks

services:
  base:
    build:
      context: ../../..
      dockerfile: *dockerfile
    image: *image
    volumes:
      - *ach-volume
    working_dir: *working-dir
  jupyter:
    extends:
      file: *docker-compose-base
      service: jupyter
    image: *image
    volumes:
      - *ach-volume
    working_dir: *working-dir
  nsight:
    extends:
      file: *docker-compose-base
      service: nsight
    volumes:
      - *ach-volume
    working_dir: *working-dir
